spring:
  application:
#    name: FORM # 서버
    name: FORM_TEST

  datasource:
#    url: jdbc:mysql://localhost:3306/FORM_PROGRAM?createDatabaseIfNotExist=true # 서버
    url: jdbc:mysql://localhost:3306/FORM_PROGRAM_DEVELOP?createDatabaseIfNotExist=true
    username: root
    password: 980122
    driver-class-name: com.mysql.cj.jdbc.Driver
    #password: dbtjddus12

  jpa:
    hibernate:
      ddl-auto: create-drop # 앱 실행시 테이블 생성, 앱 종료시 테이블 삭제

    show-sql: true

    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql # 앱 실행 시, 초기 삽입 데이터

server:
  port: 8081
#  port: 8080 # 서버
